// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using HealthCareAB_v1.Repositories.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthCareAB_v1.Migrations
{
    [ExcludeFromCodeCoverage]
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("HealthCareAB_v1.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CaregiverDailyScheduleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("PatientUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimeSlotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CaregiverDailyScheduleId");

                    b.HasIndex("PatientUserId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HealthCareAB_v1.Models.Caregiver", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.ToTable("Caregivers");
                });

            modelBuilder.Entity("HealthCareAB_v1.Models.CaregiverDailySchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaregiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaregiverStatusId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaregiverId");

                    b.HasIndex("CaregiverStatusId");

                    b.ToTable("CaregiverDailySchedules");
                });

            modelBuilder.Entity("HealthCareAB_v1.Models.CaregiverStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CaregiverStatuses");
                });

            modelBuilder.Entity("HealthCareAB_v1.Models.Patient", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SocialSecurityNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HealthCareAB_v1.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("HealthCareAB_v1.Models.TimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("HealthCareAB_v1.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HealthCareAB_v1.Models.Booking", b =>
                {
                    b.HasOne("HealthCareAB_v1.Models.CaregiverDailySchedule", null)
                        .WithMany("Bookings")
                        .HasForeignKey("CaregiverDailyScheduleId");

                    b.HasOne("HealthCareAB_v1.Models.Patient", "Patient")
                        .WithMany("Bookings")
                        .HasForeignKey("PatientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthCareAB_v1.Models.TimeSlot", "TimeSlot")
                        .WithMany("Bookings")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("HealthCareAB_v1.Models.Caregiver", b =>
                {
                    b.HasOne("HealthCareAB_v1.Models.User", "User")
                        .WithOne("Caregiver")
                        .HasForeignKey("HealthCareAB_v1.Models.Caregiver", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthCareAB_v1.Models.CaregiverDailySchedule", b =>
                {
                    b.HasOne("HealthCareAB_v1.Models.Caregiver", "Caregiver")
                        .WithMany()
                        .HasForeignKey("CaregiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthCareAB_v1.Models.CaregiverStatus", "CaregiverStatus")
                        .WithMany("CaregiverDailySchedules")
                        .HasForeignKey("CaregiverStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caregiver");

                    b.Navigation("CaregiverStatus");
                });

            modelBuilder.Entity("HealthCareAB_v1.Models.Patient", b =>
                {
                    b.HasOne("HealthCareAB_v1.Models.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("HealthCareAB_v1.Models.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthCareAB_v1.Models.Review", b =>
                {
                    b.HasOne("HealthCareAB_v1.Models.Patient", "Patient")
                        .WithOne("Review")
                        .HasForeignKey("HealthCareAB_v1.Models.Review", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthCareAB_v1.Models.CaregiverDailySchedule", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HealthCareAB_v1.Models.CaregiverStatus", b =>
                {
                    b.Navigation("CaregiverDailySchedules");
                });

            modelBuilder.Entity("HealthCareAB_v1.Models.Patient", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("HealthCareAB_v1.Models.TimeSlot", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HealthCareAB_v1.Models.User", b =>
                {
                    b.Navigation("Caregiver");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
